### PR TITLE
bug25-fix

### PR DESCRIPTION
**Pull request by himanshusoni30**
- Fixed all the page locators
- Cleaned up old code
- Removed redundant code

### CODE REVIEW

**Comment by pravee42** [comment]
@himanshusoni30 please upload the working screen shots

**Comment by himanshusoni30** [comment]
> @himanshusoni30 please upload the working screen shots

could you please pull the changes and execute on your machine to see the working changes?

**Comment by pravee42** [comment]
sure

**Comment by pravee42** [comment]
Screenshot 2024-10-17 at 6 25 53 PM

see the error it is not properly working the page locators has some issue

**Comment by himanshusoni30** [comment]
> Screenshot 2024-10-17 at 6 25 53 PM
> 
> see the error it is not properly working the page locators has some issue

it worked on my machine, i am using Ubuntu. It could be issue with macOS it seems. Can you try to search the element using SEARCH_BOX locator on your chrome browser?

**Comment by pravee42** [comment]
#27 #25

**Pull request merged**
